### ISSUE TITLE
Nuget package error

### ISSUE THREAD

**Issue by uponatime2019** [ByteDev/ByteDev.Giphy#1]
I try with code from Nuget package, it show error "Error with request. HTTP response code: 'Unauthorized'.  Message: 'No API key found in request'."
But download repos and try it's working

**Comment by ByteDev** [comment]
Some questions:
- Which type (GiphyApiClient or GiphyStickerApiClient) and method are you calling?
- What version of the nuget package are you using?
- Are you supplying your own valid API key on the request object?

Feel free to share the full response / exception etc.

Thanks

**Comment by uponatime2019** [comment]
ApiKey is correct, I tried successful with other github repos. I think problem is project type. I created Console App (Net Framework 4.7.2, HttpClient 4.2.0 - your sample is NetCore 3.0, HttpClient 4.2.2)

**Comment by ByteDev** [comment]
Yes I can see the exception now (using a 472 framework console app). I will look into it. Thanks for highlighting.

**Comment by uponatime2019** [comment]
Yep no problem

**Comment by ByteDev** [comment]
FYI it would appear that the previous version of the package, 4.0.2, works fine with framework 4.7.2.  You can try using that until I figure out whats gone wrong when the consuming app is framework.

**Comment by ByteDev** [comment]
This bug is now fixed in nuget package version: 5.0.1.

The bug was something to do with the UriBuilder implementation and only seems to show up when the consuming app is .NET Framework.

I've added a test app project ByteDev.Giphy.TestApp472 that uses the nuget package 5.0.1 and it seems to work fine now (it didn't before I added my fix).

Thanks
